/*
Copyright 2025 The llm-d-inference-sim Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Contains structures and functions related to responses for all supported APIs
package api

import (
	"encoding/json"
	"errors"
	"strings"

	"github.com/valyala/fasthttp"
)

const (
	chatComplIDPrefix             = "chatcmpl-"
	textComplIDPrefix             = "cmpl-"
	ResponsesIDPrefix             = "resp_"
	ResponsesMessageIDPrefix      = "msg_"
	ResponsesFunctionCallIDPrefix = "fc_"
	ResponsesCallIDPrefix         = "call_"
	TextCompletionObject          = "text_completion"
	ChatCompletionObject          = "chat.completion"
	ChatCompletionChunkObject     = "chat.completion.chunk"
	ResponsesObject               = "response"
	ResponsesStatusCompleted      = "completed"
	ResponsesStatusInProgress     = "in_progress"
	ResponsesOutputText           = "output_text"
	ResponsesOutputMessage        = "message"
	ResponsesOutputFunctionCall   = "function_call"

	SSEDoneMarker = "[DONE]"
	SSEDataPrefix = "data: "
)

// Response interface representing response types
type Response interface {
	GetRequestID() string
}

// baseResponse contains base response related information
type baseResponse struct {
	// ID defines the response ID
	ID string `json:"id,omitempty"`
	// Model defines the Model name for current request
	Model string `json:"model,omitempty"`
	// Object is the Object type, "text_completion", "chat.completion", or "chat.completion.chunk"
	Object string `json:"object,omitempty"`
	// KVParams kv transfer related fields
	KVParams *KVTransferParams `json:"kv_transfer_params,omitempty"`
	// RequestID is the unique request ID for tracking
	RequestID string `json:"-"`
}

// baseCompletionsResponse contains base completions response related information
type baseCompletionsResponse struct {
	baseResponse
	// Created defines the response creation timestamp
	Created int64 `json:"created"`
	// Usage contains the token usage statistics for the request
	Usage *Usage `json:"usage"`
}

// Usage contains token Usage statistics
type Usage struct {
	// PromptTokens is the number of tokens in the prompt
	PromptTokens int `json:"prompt_tokens"`
	// CompletionTokens is the number of tokens generated by the model as the response
	CompletionTokens int `json:"completion_tokens"`
	// TotalTokens is the total number of tokens processed for the request (the sum of the two values above)
	TotalTokens int `json:"total_tokens"`
	// PromptTokensDetails contains detailed token usage statistics for the prompt
	PromptTokensDetails *PromptTokensDetails `json:"prompt_tokens_details"`
}

// PromptTokensDetails contains detailed token usage statistics for the prompt
type PromptTokensDetails struct {
	// CacheTokens is the number of tokens in the prompt that are in the local KV Cache
	CachedTokens int `json:"cached_tokens"`
}

// LogprobsContent represents logprobs for a single token in chat completions
type LogprobsContent struct {
	// Token is the token string
	Token string `json:"token"`
	// Logprob is the log probability of the token
	Logprob float64 `json:"logprob"`
	// Bytes is the byte representation of the token
	Bytes []int `json:"bytes"`
	// TopLogprobs is the list of top alternative tokens along their log probabilities
	TopLogprobs []LogprobsContent `json:"top_logprobs,omitempty"`
}

// ChatLogprobs represents logprobs for chat completion responses
type ChatLogprobs struct {
	// Content is an array of logprobs for each token in the content
	Content []LogprobsContent `json:"content"`
}

// TextLogprobs represents logprobs for text completion responses
type TextLogprobs struct {
	// Tokens is an array of tokens
	Tokens []string `json:"tokens"`
	// TokenLogprobs is an array of log probabilities for each token
	TokenLogprobs []float64 `json:"token_logprobs"`
	// TopLogprobs is an array of objects containing the top alternative tokens
	TopLogprobs []map[string]float64 `json:"top_logprobs"`
	// TextOffset is an array of character offsets
	TextOffset []int `json:"text_offset"`
}

// ChatCompletionsResponse defines structure of /chat/completions response
type ChatCompletionsResponse struct {
	baseCompletionsResponse
	// Choices list of Choices of the response, according of OpenAI API
	Choices []ChatRespChoice `json:"choices"`
	// ECTransferParams holds simulated encoder-cache transfer params per mm hash
	ECTransferParams map[string]ECTransferParams `json:"ec_transfer_params,omitempty"`
}

// baseResponseChoice contains base completions response's choice related information
type baseResponseChoice struct {
	// Index defines completions response choice Index
	Index int `json:"index"`
	// FinishReason defines finish reason for response or for chunks, for not last chunks is defined as null
	FinishReason *string `json:"finish_reason"`
}

// v1/chat/completions
// Message defines chat completions Message
type Message struct {
	// Role is the message Role, optional values are 'user', 'assistant', 'tool', ...
	Role string `json:"role,omitempty"`
	// Content defines text of this message
	Content ChatComplContent `json:"content,omitempty"`
	// ToolCalls are the tool calls created by the model
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`
	// ToolCallID is the ID of the tool call this message is responding to (role: "tool" only)
	ToolCallID string `json:"tool_call_id,omitempty"`
}

// MarshalJSON omits the content field entirely when it carries no data
// (empty Raw and nil Structured), so finish-reason-only deltas marshal as
// {"role":...} or {} rather than {"content":""}.
func (m Message) MarshalJSON() ([]byte, error) {
	type alias struct {
		Role       string            `json:"role,omitempty"`
		Content    *ChatComplContent `json:"content,omitempty"`
		ToolCalls  []ToolCall        `json:"tool_calls,omitempty"`
		ToolCallID string            `json:"tool_call_id,omitempty"`
	}
	a := alias{Role: m.Role, ToolCalls: m.ToolCalls, ToolCallID: m.ToolCallID}
	if m.Content.Raw != "" || len(m.Content.Structured) > 0 {
		a.Content = &m.Content
	}
	return json.Marshal(a)
}

func (m *Message) PlainText(includeRole bool) string {
	var builder strings.Builder

	if includeRole {
		builder.WriteString(m.Role)
		if m.ToolCallID != "" {
			builder.WriteString("(")
			builder.WriteString(m.ToolCallID)
			builder.WriteString(")")
		}
		builder.WriteString(": ")
	}

	if m.Content.Raw != "" {
		builder.WriteString(m.Content.Raw)
	} else {
		var parts []string
		for _, block := range m.Content.Structured {
			switch block.Type {
			case ContentTypeText:
				parts = append(parts, block.Text)
			case "image_url":
				if block.ImageURL != nil {
					parts = append(parts, "image: "+block.ImageURL.Url)
				}
			case "audio_url":
				if block.AudioURL != nil {
					parts = append(parts, "audio: "+block.AudioURL.Url)
				}
			case "input_audio":
				if block.InputAudio != nil {
					parts = append(parts, "input_audio: "+block.InputAudio.Format)
				}
			case "video_url":
				if block.VideoURL != nil {
					parts = append(parts, "video: "+block.VideoURL.Url)
				}
			}
		}

		builder.WriteString(strings.Join(parts, "\n"))
	}

	for _, tc := range m.ToolCalls {
		if tc.Function.Name != nil {
			builder.WriteString("[")
			builder.WriteString(*tc.Function.Name)
			builder.WriteString("(")
			builder.WriteString(tc.Function.Arguments)
			builder.WriteString(")]")
		}
	}

	return builder.String()
}

type ChatComplContent struct {
	Raw        string
	Structured []ChatComplContentBlock
}

type ChatComplContentBlock struct {
	Type       string                    `json:"type"`
	Text       string                    `json:"text,omitempty"`
	ImageURL   *ChatComplURLBlock        `json:"image_url,omitempty"`
	InputAudio *ChatComplInputAudioBlock `json:"input_audio,omitempty"`
	AudioURL   *ChatComplURLBlock        `json:"audio_url,omitempty"`
	VideoURL   *ChatComplURLBlock        `json:"video_url,omitempty"`
}

type ChatComplURLBlock struct {
	Url string `json:"url,omitempty"`
}

type ChatComplInputAudioBlock struct {
	Data   string `json:"data,omitempty"`
	Format string `json:"format,omitempty"`
}

// UnmarshalJSON allow use both format
func (mc *ChatComplContent) UnmarshalJSON(data []byte) error {
	// Raw format
	var str string
	if err := json.Unmarshal(data, &str); err == nil {
		mc.Raw = str
		return nil
	}

	// Block format
	var blocks []ChatComplContentBlock
	if err := json.Unmarshal(data, &blocks); err == nil {
		mc.Structured = blocks
		return nil
	}

	return errors.New("content format not supported")
}

func (mc ChatComplContent) MarshalJSON() ([]byte, error) {
	if mc.Raw != "" {
		return json.Marshal(mc.Raw)
	}
	if mc.Structured != nil {
		return json.Marshal(mc.Structured)
	}
	return json.Marshal("")
}

// FunctionCall defines a tool call generated by the model including its arguments
type FunctionCall struct {
	// Name is the function's name, can be null in streaming in not the first chunk
	Name *string `json:"name"`
	// Arguments are the arguments of the function call
	Arguments string `json:"arguments,omitempty"`
	// TokenizedArguments contains tokenized arguments
	tokenizedArguments *Tokenized
}

func (fc *FunctionCall) SetTokenizedArguments(tokenized *Tokenized) {
	fc.tokenizedArguments = tokenized
}

func (fc *FunctionCall) TokenizedArguments() *Tokenized {
	return fc.tokenizedArguments
}

// ToolCall defines a tool call generated by the model
type ToolCall struct {
	// Function is a tool call generated by the model
	Function FunctionCall `json:"function"`
	// ID is the ID of the tool call
	ID string `json:"id"`
	// Type is the type of the tool, only functions are supported
	Type string `json:"type"`
	// Index is the index of the tool in the sequence of tools generated by the model
	Index int `json:"index"`
}

// ChatRespChoice represents a single chat completions response choice
type ChatRespChoice struct {
	baseResponseChoice
	// Message contains choice's Message
	Message Message `json:"message"`
	// Logprobs contains the log probabilities for the response
	Logprobs *ChatLogprobs `json:"logprobs,omitempty"`
}

// TextCompletionsResponse defines structure of /completions response
type TextCompletionsResponse struct {
	baseCompletionsResponse
	// Choices list of Choices of the response, according of OpenAI API
	Choices []TextRespChoice `json:"choices"`
}

// TextRespChoice represents a single text completions response choice
type TextRespChoice struct {
	baseResponseChoice
	// Text defines request's content
	Text string `json:"text"`
	// Logprobs contains the log probabilities for the response
	Logprobs *TextLogprobs `json:"logprobs,omitempty"`
}

// CompletionsRespChunk is an interface that defines a single response chunk
type CompletionsRespChunk interface{}

// ChatCompletionsRespChunk is a single chat completions response chunk
type ChatCompletionsRespChunk struct {
	baseCompletionsResponse
	// Choices list of Choices of the response, according of OpenAI API
	Choices []ChatRespChunkChoice `json:"choices"`
	// Modality is set to "image" on the synthetic image chunk sent after tokens.
	Modality string `json:"modality,omitempty"`
}

// ChatRespChunkChoice represents a single chat completions response choice in case of streaming
type ChatRespChunkChoice struct {
	baseResponseChoice
	// Delta is a content of the chunk
	Delta Message `json:"delta"`
	// Logprobs contains the log probabilities for the response chunk
	Logprobs *ChatLogprobs `json:"logprobs,omitempty"`
}

// GenerationResponse defines structure of generation response
type GenerationResponse struct {
	baseCompletionsResponse
	Tokenized *Tokenized
}

// Error defines the simulator's response in case of an error
type Error struct {
	// Message is an error Message
	Message string `json:"message"`
	// Type is a type of the error
	Type string `json:"type"`
	// Param is the error's parameter
	Param *string `json:"param"`
	// Code is the error code integer (same as HTTP status code)
	Code int `json:"code,omitempty"`
}

// NewError creates a new CompletionError
func NewError(message string, code int, param *string) Error {
	return Error{
		Message: message,
		Code:    code,
		Type:    ErrorCodeToType(code),
		Param:   param,
	}
}

// ErrorResponse wraps the error in the expected OpenAI format
type ErrorResponse struct {
	Error Error `json:"error"`
}

// ErrorCodeToType maps error code to error type according to https://www.npmjs.com/package/openai
func ErrorCodeToType(code int) string {
	errorType := ""
	switch code {
	case fasthttp.StatusBadRequest:
		errorType = "BadRequestError"
	case fasthttp.StatusUnauthorized:
		errorType = "AuthenticationError"
	case fasthttp.StatusForbidden:
		errorType = "PermissionDeniedError"
	case fasthttp.StatusNotFound:
		errorType = "NotFoundError"
	case fasthttp.StatusUnprocessableEntity:
		errorType = "UnprocessableEntityError"
	case fasthttp.StatusTooManyRequests:
		errorType = "RateLimitError"
	default:
		if code >= fasthttp.StatusInternalServerError {
			errorType = "InternalServerError"
		} else {
			errorType = "APIConnectionError"
		}
	}
	return errorType
}

func CreateBaseResponseChoice(index int, finishReason *string) baseResponseChoice {
	return baseResponseChoice{Index: index, FinishReason: finishReason}
}

func CreateChatRespChoice(base baseResponseChoice, message Message) ChatRespChoice {
	return ChatRespChoice{baseResponseChoice: base, Message: message, Logprobs: nil}
}

func CreateChatRespChunkChoice(base baseResponseChoice, message Message) ChatRespChunkChoice {
	return ChatRespChunkChoice{baseResponseChoice: base, Delta: message, Logprobs: nil}
}

func CreateTextRespChoice(base baseResponseChoice, text string) TextRespChoice {
	return TextRespChoice{baseResponseChoice: base, Text: text, Logprobs: nil}
}

func CreateBaseCompletionsResponse(created int64, model string, usage *Usage, requestID string, doRemoteDecode bool) baseCompletionsResponse {
	baseResp := baseCompletionsResponse{
		baseResponse: baseResponse{
			Model:     model,
			RequestID: requestID,
		},
		Created: created,
		Usage:   usage,
	}
	if doRemoteDecode {
		baseResp.KVParams = BuildPrefillKVTransferParams()
	}
	return baseResp
}

// BuildPrefillKVTransferParams returns a KVTransferParams populated with the
// hard-coded "this pod did the prefill" values used by the simulator across all
// completion-style endpoints. The fields are placeholders — a real prefill pod
// would set these from its own engine/host/port and the blocks it produced.
func BuildPrefillKVTransferParams() *KVTransferParams {
	return &KVTransferParams{
		DoRemoteDecode:  false,
		DoRemotePrefill: true,
		RemoteBlockIds:  []string{"DUMMY_ID"},
		RemoteEngineId:  "DUMMY_ID",
		RemoteHost:      "DUMMY",
		RemotePort:      1234,
		TPSize:          1,
	}
}

// GetRequestID returns the request ID from the response
func (b baseResponse) GetRequestID() string {
	return b.RequestID
}

func CreateChatCompletionsResponse(base baseCompletionsResponse, choices []ChatRespChoice) *ChatCompletionsResponse {
	base.ID = chatComplIDPrefix + base.RequestID
	return &ChatCompletionsResponse{baseCompletionsResponse: base, Choices: choices}
}

func CreateTextCompletionsResponse(base baseCompletionsResponse, choices []TextRespChoice) *TextCompletionsResponse {
	base.ID = textComplIDPrefix + base.RequestID
	return &TextCompletionsResponse{baseCompletionsResponse: base, Choices: choices}
}

func CreateChatCompletionsRespChunk(base baseCompletionsResponse, choices []ChatRespChunkChoice) *ChatCompletionsRespChunk {
	base.ID = chatComplIDPrefix + base.RequestID
	return &ChatCompletionsRespChunk{baseCompletionsResponse: base, Choices: choices}
}

// CreateImageModalityChunk builds the synthetic image SSE chunk sent after the
// token stream when X-Send-Image is set. The chunk has the same structure as a
// text chunk but carries modality "image" and an image_url content block.
func CreateImageModalityChunk(base baseCompletionsResponse, choiceIdx int, imageData string) *ChatCompletionsRespChunk {
	chunk := CreateChatCompletionsRespChunk(base, []ChatRespChunkChoice{
		CreateChatRespChunkChoice(
			CreateBaseResponseChoice(choiceIdx, nil),
			Message{Content: ChatComplContent{Structured: []ChatComplContentBlock{
				{Type: "image_url", ImageURL: &ChatComplURLBlock{Url: "data:image/png;base64," + imageData}},
			}}}),
	})
	chunk.Modality = "image"
	return chunk
}

func CreateGenerationResponse(base baseCompletionsResponse, tokens *Tokenized) *GenerationResponse {
	return &GenerationResponse{baseCompletionsResponse: base, Tokenized: tokens}
}

func CreateResponsesResponse(model string, requestID string, createdAt int64,
	instructions *string, output []OutputItem, usage *ResponsesUsage) *ResponsesResponse {
	return &ResponsesResponse{
		baseResponse: baseResponse{
			ID:        ResponsesIDPrefix + requestID,
			Model:     model,
			Object:    ResponsesObject,
			RequestID: requestID,
		},
		CreatedAt:    createdAt,
		Status:       ResponsesStatusCompleted,
		Instructions: instructions,
		Text:         &TextSettings{Format: &TextFormat{Type: ContentTypeText}},
		Output:       output,
		Usage:        usage,
	}
}

// Responses

type OutputItem interface {
	isOutputItem()
	json.Marshaler
}

type ResponsesResponse struct {
	baseResponse
	CreatedAt    int64           `json:"created_at,omitempty"`
	Status       string          `json:"status,omitempty"`
	Instructions *string         `json:"instructions,omitempty"`
	Output       []OutputItem    `json:"output,omitempty"`
	Text         *TextSettings   `json:"text,omitempty"`
	Usage        *ResponsesUsage `json:"usage,omitempty"`
	Error        *Error          `json:"error,omitempty"`
	Store        *bool           `json:"store,omitempty"`
}

type MessageOutput struct {
	Type    string          `json:"type"` // message
	ID      string          `json:"id,omitempty"`
	Role    string          `json:"role"` // assistant
	Status  string          `json:"status,omitempty"`
	Content []OutputContent `json:"content"`
}

func (MessageOutput) isOutputItem() {}

func (m MessageOutput) MarshalJSON() ([]byte, error) {
	if m.Type == "" {
		m.Type = ResponsesOutputMessage
	}
	type alias MessageOutput
	return json.Marshal(alias(m))
}

// FunctionCallOutputItem is a function_call item in a Responses API output array.
type FunctionCallOutputItem struct {
	Type      string `json:"type"` // function_call
	ID        string `json:"id,omitempty"`
	CallID    string `json:"call_id,omitempty"`
	Name      string `json:"name,omitempty"`
	Arguments string `json:"arguments,omitempty"`
	Status    string `json:"status,omitempty"`
}

func (FunctionCallOutputItem) isOutputItem() {}

func (f FunctionCallOutputItem) MarshalJSON() ([]byte, error) {
	if f.Type == "" {
		f.Type = ResponsesOutputFunctionCall
	}
	if f.Status == "" {
		f.Status = ResponsesStatusCompleted
	}
	type alias FunctionCallOutputItem
	return json.Marshal(alias(f))
}

// TopLogprob represents a top alternative token in Responses API logprobs
type TopLogprob struct {
	Token   string  `json:"token"`
	Logprob float64 `json:"logprob"`
	Bytes   []int   `json:"bytes"`
}

// ResponsesLogprob represents logprobs for a single token in the Responses API
type ResponsesLogprob struct {
	Token       string       `json:"token"`
	Logprob     float64      `json:"logprob"`
	Bytes       []int        `json:"bytes"`
	TopLogprobs []TopLogprob `json:"top_logprobs"`
}

type OutputContent struct {
	Type string `json:"type"` // output_text
	Text string `json:"text,omitempty"`
	// nil ptr → omit (not requested); non-nil ptr to nil slice → null; non-nil ptr to empty slice → [];
	// non-nil ptr to populated slice → full array
	Logprobs *[]ResponsesLogprob `json:"logprobs,omitempty"`
}

func (c OutputContent) MarshalJSON() ([]byte, error) {
	if c.Type == "" {
		c.Type = ResponsesOutputText
	}
	type alias OutputContent
	return json.Marshal(alias(c))
}

type ResponsesUsage struct {
	InputTokens  int `json:"input_tokens,omitempty"`
	OutputTokens int `json:"output_tokens,omitempty"`
	TotalTokens  int `json:"total_tokens,omitempty"`
}

// Responses API streaming event types
const (
	ResponsesEventCreated                    = "response.created"
	ResponsesEventInProgress                 = "response.in_progress"
	ResponsesEventOutputItemAdded            = "response.output_item.added"
	ResponsesEventContentPartAdded           = "response.content_part.added"
	ResponsesEventTextDelta                  = "response.output_text.delta"
	ResponsesEventTextLogprobsDelta          = "response.output_text.logprobs.delta"
	ResponsesEventTextDone                   = "response.output_text.done"
	ResponsesEventContentPartDone            = "response.content_part.done"
	ResponsesEventFunctionCallArgumentsDelta = "response.function_call_arguments.delta"
	ResponsesEventFunctionCallArgumentsDone  = "response.function_call_arguments.done"
	ResponsesEventOutputItemDone             = "response.output_item.done"
	ResponsesEventCompleted                  = "response.completed"
)

// ResponsesResponseEvent is used for events that carry a full response object
// (response.created, response.in_progress, response.completed).
type ResponsesResponseEvent struct {
	Type     string             `json:"type"`
	Response *ResponsesResponse `json:"response"`
}

// ResponsesItemEvent is used for all item/content/text streaming events
// (output_item.added/done, content_part.added/done, output_text.delta/done,
// output_text.logprobs.delta, function_call_arguments.delta/done).
// Fields not relevant to a given event type are omitted via omitempty.
type ResponsesItemEvent struct {
	Type         string              `json:"type"`
	OutputIndex  int                 `json:"output_index,omitempty"`
	ContentIndex int                 `json:"content_index,omitempty"`
	ItemID       string              `json:"item_id,omitempty"`
	Item         OutputItem          `json:"item,omitempty"`
	Part         *OutputContent      `json:"part,omitempty"`
	Delta        string              `json:"delta,omitempty"`
	Text         string              `json:"text,omitempty"`
	Name         string              `json:"name,omitempty"`
	Arguments    string              `json:"arguments,omitempty"`
	Logprobs     *[]ResponsesLogprob `json:"logprobs,omitempty"`
}

// Generate

// GenerateResponse defines structure of generate response
type GenerateResponse struct {
	baseResponse
	Choices          []GenerateRespChoice        `json:"choices"`
	GenRequestID     string                      `json:"request_id"`
	ECTransferParams map[string]ECTransferParams `json:"ec_transfer_params"`
}

type GenerateRespChoice struct {
	baseResponseChoice
	TokenIDs []uint32 `json:"token_ids"`
}

type GenerateStreamResponse struct {
	RequestID string               `json:"request_id"`
	Choices   []GenerateRespChoice `json:"choices"`
	Usage     *Usage               `json:"usage,omitempty"`
}

type ECTransferParams struct {
	PeerHost      string `json:"peer_host"`
	PeerPort      int    `json:"peer_port"`
	SizeBytes     int    `json:"size_bytes"`
	NixlAgentData []byte `json:"nixl_agent_metadata_b64"`
}

// Anthropic Messages API

const (
	MessagesIDPrefix            = "msg_"
	MessagesType                = "message"
	MessagesStopReasonEndTurn   = "end_turn"
	MessagesStopReasonToolUse   = "tool_use"
	MessagesStopReasonMaxTokens = "max_tokens"

	MessagesEventMessageStart      = "message_start"
	MessagesEventContentBlockStart = "content_block_start"
	MessagesEventPing              = "ping"
	MessagesEventContentBlockDelta = "content_block_delta"
	MessagesEventContentBlockStop  = "content_block_stop"
	MessagesEventMessageDelta      = "message_delta"
	MessagesEventMessageStop       = "message_stop"

	ContentTypeText = "text"
)

// MessagesUsage contains token usage for the Anthropic Messages API.
type MessagesUsage struct {
	InputTokens              int `json:"input_tokens"`
	CacheCreationInputTokens int `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int `json:"cache_read_input_tokens"`
	OutputTokens             int `json:"output_tokens"`
}

// MessagesStreamUsage carries only output_tokens in streaming delta events.
type MessagesStreamUsage struct {
	OutputTokens int `json:"output_tokens"`
}

// MessagesContentBlock is a single content block in a Messages API response.
// Type is "text" (text field) or "tool_use" (ID, Name, Input fields).
type MessagesContentBlock struct {
	Type  string         `json:"type"`
	Text  string         `json:"text,omitempty"`
	ID    string         `json:"id,omitempty"`
	Name  string         `json:"name,omitempty"`
	Input map[string]any `json:"input,omitempty"`
}

// MessagesResponse is the non-streaming Anthropic /v1/messages response.
type MessagesResponse struct {
	ID           string                 `json:"id"`
	Type         string                 `json:"type"`
	Role         string                 `json:"role"`
	Content      []MessagesContentBlock `json:"content"`
	Model        string                 `json:"model"`
	StopReason   *string                `json:"stop_reason"`
	StopSequence *string                `json:"stop_sequence"`
	Usage        MessagesUsage          `json:"usage"`
	RequestID    string                 `json:"-"`
}

func (r *MessagesResponse) GetRequestID() string { return r.RequestID }

// CreateMessagesResponse builds a complete non-streaming Messages API response.
func CreateMessagesResponse(model, requestID, stopReason string,
	content []MessagesContentBlock, usage MessagesUsage) *MessagesResponse {
	sr := stopReason
	if content == nil {
		content = []MessagesContentBlock{}
	}
	return &MessagesResponse{
		ID:           MessagesIDPrefix + requestID,
		Type:         MessagesType,
		Role:         RoleAssistant,
		Content:      content,
		Model:        model,
		StopReason:   &sr,
		StopSequence: nil,
		Usage:        usage,
		RequestID:    requestID,
	}
}

// CreateMessagesStreamStartMessage builds the initial message object for the
// message_start streaming event: empty content, nil stop_reason, input_tokens set.
func CreateMessagesStreamStartMessage(model, requestID string, inputTokens int) *MessagesResponse {
	return &MessagesResponse{
		ID:           MessagesIDPrefix + requestID,
		Type:         MessagesType,
		Role:         RoleAssistant,
		Content:      []MessagesContentBlock{},
		Model:        model,
		StopReason:   nil,
		StopSequence: nil,
		Usage:        MessagesUsage{InputTokens: inputTokens},
		RequestID:    requestID,
	}
}

// Streaming event structs

type MessagesMessageStartEvent struct {
	Type    string            `json:"type"`
	Message *MessagesResponse `json:"message"`
}

// MessagesContentBlockStart is the content block carried by a content_block_start
// event. It differs from MessagesContentBlock in one way that matters on the wire:
// Text is a pointer, so a text block serialises "text":"" instead of dropping the
// field. Clients accumulate text deltas onto this block, and one that arrives
// without the field starts from null - the Anthropic API always sends "".
type MessagesContentBlockStart struct {
	Type  string         `json:"type"`
	Text  *string        `json:"text,omitempty"`
	ID    string         `json:"id,omitempty"`
	Name  string         `json:"name,omitempty"`
	Input map[string]any `json:"input,omitempty"`
}

type MessagesContentBlockStartEvent struct {
	Type         string                    `json:"type"`
	Index        int                       `json:"index"`
	ContentBlock MessagesContentBlockStart `json:"content_block"`
}

// MessagesContentBlockDelta is the delta payload inside a content_block_delta event.
// Type is "text_delta" (Text field) or "input_json_delta" (PartialJSON field).
type MessagesContentBlockDelta struct {
	Type        string `json:"type"`
	Text        string `json:"text,omitempty"`
	PartialJSON string `json:"partial_json,omitempty"`
}

type MessagesContentBlockDeltaEvent struct {
	Type  string                    `json:"type"`
	Index int                       `json:"index"`
	Delta MessagesContentBlockDelta `json:"delta"`
}

type MessagesContentBlockStopEvent struct {
	Type  string `json:"type"`
	Index int    `json:"index"`
}

type MessagesMessageDeltaPayload struct {
	StopReason   *string `json:"stop_reason"`
	StopSequence *string `json:"stop_sequence"`
}

type MessagesMessageDeltaEvent struct {
	Type  string                      `json:"type"`
	Delta MessagesMessageDeltaPayload `json:"delta"`
	Usage MessagesStreamUsage         `json:"usage"`
}

type MessagesMessageStopEvent struct {
	Type string `json:"type"`
}

type MessagesPingEvent struct {
	Type string `json:"type"`
}
